<a href="https://colab.research.google.com/github/Parvathyyy/case/blob/main/ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np
path = "https://github.com/Parvathyyy/case/raw/main/Churn_Rate_Prediction.csv"
data = pd.read_csv(path)
data.head()


RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [8]:
data.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [9]:
x = data.iloc[:,3:13]
y = data.iloc[:,13]

In [10]:
x.head()

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [11]:
x = pd.get_dummies(x, drop_first = True)

In [12]:
x.head()

CreditScore  Age  Tenure  ...  Geography_Germany  Geography_Spain  Gender_Male
0          619   42       2  ...                  0                0            0
1          608   41       1  ...                  0                1            0
2          502   42       8  ...                  0                0            0
3          699   39       1  ...                  0                0            0
4          850   43       2  ...                  0                1            0

[5 rows x 11 columns]

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x= sc.fit_transform(x)

In [20]:
x

array([[-0.32622142,  0.29351742, -1.04175968, ..., -0.57873591,
        -0.57380915, -1.09598752],
       [-0.44003595,  0.19816383, -1.38753759, ..., -0.57873591,
         1.74273971, -1.09598752],
       [-1.53679418,  0.29351742,  1.03290776, ..., -0.57873591,
        -0.57380915, -1.09598752],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -0.57873591,
        -0.57380915, -1.09598752],
       [ 1.25683526,  0.29351742, -0.69598177, ...,  1.72790383,
        -0.57380915,  0.91241915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -0.57873591,
        -0.57380915, -1.09598752]])

In [21]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [22]:
import keras
from tensorflow.keras.models import Sequential
from keras.layers import Dense

In [25]:
classifier = Sequential()

In [26]:
classifier.add(Dense(units = 6,kernel_initializer='he_uniform',activation= 'relu',input_dim =11))

In [27]:
classifier.add(Dense(units = 6,kernel_initializer='he_uniform',activation= 'relu'))

In [30]:
classifier.add(Dense(units = 1,kernel_initializer='glorot_uniform',activation= 'sigmoid'))

In [33]:

classifier.compile(optimizer = 'adam',loss ='binary_crossentropy', metrics =['Accuracy'])

In [35]:
classifier.fit(x_train,y_train, batch_size= 10, epochs=50)

Epoch 1/50
800/800 [==============================] - 1s 2ms/step - loss: 3.6241 - Accuracy: 0.1030
Epoch 2/50
800/800 [==============================] - 1s 2ms/step - loss: 3.6241 - Accuracy: 0.1030
Epoch 3/50
800/800 [==============================] - 1s 2ms/step - loss: 3.6241 - Accuracy: 0.1030
Epoch 4/50
800/800 [==============================] - 1s 2ms/step - loss: 3.6241 - Accuracy: 0.1030
Epoch 5/50
800/800 [==============================] - 1s 2ms/step - loss: 3.6241 - Accuracy: 0.1030
Epoch 6/50
800/800 [==============================] - 1s 2ms/step - loss: 3.6241 - Accuracy: 0.1030
Epoch 7/50
800/800 [==============================] - 1s 2ms/step - loss: 3.6241 - Accuracy: 0.1030
Epoch 8/50
800/800 [==============================] - 1s 2ms/step - loss: 3.6241 - Accuracy: 0.1030
Epoch 9/50
800/800 [==============================] - 1s 2ms/step - loss: 3.6241 - Accuracy: 0.1030
Epoch 10/50
800/800 [==============================] - 1s 2ms/step - loss: 3.6241 - Accuracy: 0.1030

In [36]:
y_pred = classifier.predict(x_test)

In [37]:
y_pred

array([[-0.5538505 , -0.37395772,  1.0329077 , ...,  1.7279038 ,
        -0.57380915, -1.0959876 ],
       [-1.3195119 ,  0.10281024, -1.0417597 , ..., -0.5787359 ,
        -0.57380915, -1.0959876 ],
       [ 0.5739481 ,  0.2935174 ,  1.0329077 , ..., -0.5787359 ,
         1.7427397 , -1.0959876 ],
       ...,
       [-0.7504392 , -0.27860412, -1.3875376 , ..., -0.5787359 ,
         1.7427397 ,  0.91241914],
       [-0.00547137, -0.4693113 , -0.35020387, ...,  1.7279038 ,
        -0.57380915,  0.91241914],
       [-0.8021731 , -0.85072565,  1.0329077 , ...,  1.7279038 ,
        -0.57380915,  0.91241914]], dtype=float32)

In [38]:
y_pred = (y_pred > 0.5)

In [39]:
y_pred

array([[False, False,  True, ...,  True, False, False],
       [False, False, False, ..., False, False, False],
       [ True, False,  True, ..., False,  True, False],
       ...,
       [False, False, False, ..., False,  True,  True],
       [False, False, False, ...,  True, False,  True],
       [False, False,  True, ...,  True, False,  True]])

In [40]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred, y_test)

ValueError: ignored